"""initial schema — all 16 tables, constraints and indexes

Baseline migration. It materialises the entire schema directly from the
SQLAlchemy model metadata, so the very first migration is guaranteed to match
the models exactly. Subsequent migrations are normal autogenerated diffs:

    alembic revision --autogenerate -m "add X"

Revision ID: 0001_initial
Revises:
Create Date: 2026-05-17
"""
from alembic import op

from app.core.database import Base
import app.models  # noqa: F401  -- populate Base.metadata

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    # create_all respects FK dependency ordering and emits every
    # UniqueConstraint / Index / ForeignKey defined on the models.
    Base.metadata.create_all(bind=bind)


def downgrade() -> None:
    bind = op.get_bind()
    Base.metadata.drop_all(bind=bind)
